apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: letsencrypt
spec:
  dnsNames:
    - domain-name.static
  secretName: nginx-webpage-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
