apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: test@issuer.com
    privateKeySecretRef:
      name: letsencrypt-issuer-key
    solvers:
    - http01:
        ingress:
          class: traefik
